syntax = "proto3";

package pb;

import "google/api/annotations.proto";
import "common.proto";

option go_package = "github.com/lh-khanhduy/banco_de_rata/pb";

service AccountServices {
  rpc CreateAccount(CreateAccountRequest) returns (IdResponse){
    option (google.api.http) = {
      post: "/v1/create_account"
      body: "*"
    };
  }
  rpc GetAccount(GetAccountRequest) returns (AccountResponse){
    option (google.api.http) = {
      get: "/v1/get_account"
    };
  }
  rpc ListAccounts(ListAccountsRequest) returns (ListAccountResponse){
    option (google.api.http) = {
      get: "/v1/list_accounts"
    };
  }
  rpc UpdateAccount(UpdateAccountRequest) returns (AccountResponse){
    option (google.api.http) = {
      patch: "/v1/update_account"
      body : "*"
    };
  }
  rpc DeleteAccount(DeleteAccountRequest) returns (DeleteAccountResponse){
    option (google.api.http) = {
      delete: "/v1/delete_account"
    };
  }
}

message CreateAccountRequest {
  string currency = 1;
}

message GetAccountRequest {
  int64 id = 1;
}

message AccountResponse {
  Account account = 1;
}

message ListAccountsRequest {
  int32 page_id   = 1;
  int32 page_size = 2;
}

message ListAccountResponse {
  repeated Account accounts = 1;
}

message UpdateAccountRequest {
  int64 id      = 1;
  int64 balance = 2;
}

message DeleteAccountRequest {
  int64 id = 1;
}

message DeleteAccountResponse {
  int64 id = 1;
}